import type {
  Params,
  RouteCandidate,
  TransportLegVM,
  StayVM,
  DailyBudgetVM,
  CostSummaryVM,
  ItineraryDay,
} from "@/types"

export const mockParams: Params = {
  tripId: "trip-123",
  title: "European Adventure",
  currency: "USD",
  partySize: 2,
  originCity: "New York",
  originIATA: "JFK",
  windowStart: "2024-06-01",
  windowEnd: "2024-08-31",
  durationMin: 10,
  durationMax: 14,
  baggagePcs: 1,
  cabin: "Economy",
  nightBusAllowed: true,
  refundableOnly: false,
  maxHops: 2,
  regionPrefs: ["Western Europe", "Central Europe"],
  excludedCities: ["Frankfurt"],
  notes: "Prefer cultural sites and local cuisine experiences",
  dateGenerated: "2024-01-15T10:30:00Z",
  priceTimestamp: "2024-01-15T10:30:00Z",
}

export const mockRouteCandidates: RouteCandidate[] = [
  {
    id: "route-1",
    title: "Classic European Circuit",
    dateRange: "Jun 15 - Jun 28, 2024",
    hops: 1,
    legsSummary: ["JFK → CDG", "CDG → AMS", "AMS → FCO", "FCO → JFK"],
    badges: ["Baggage included", "Refundable mix", "Direct flights"],
    costs: {
      flights: 1240,
      ground: 320,
      stays: 1680,
      daily: 840,
      total: 4080,
      currency: "USD",
    },
  },
  {
    id: "route-2",
    title: "Budget Explorer Route",
    dateRange: "Jul 2 - Jul 14, 2024",
    hops: 2,
    legsSummary: ["JFK → LHR", "LHR → BER", "BER → PRG", "PRG → JFK"],
    badges: ["Overnight bus used", "Budget friendly", "Mixed transport"],
    costs: {
      flights: 890,
      ground: 180,
      stays: 980,
      daily: 560,
      total: 2610,
      currency: "USD",
    },
  },
  {
    id: "route-3",
    title: "Premium Comfort Journey",
    dateRange: "Aug 5 - Aug 17, 2024",
    hops: 0,
    legsSummary: ["JFK → ZUR", "ZUR → VIE", "VIE → MUC", "MUC → JFK"],
    badges: ["Premium economy", "Refundable", "Luxury stays"],
    costs: {
      flights: 2100,
      ground: 450,
      stays: 2800,
      daily: 1200,
      total: 6550,
      currency: "USD",
    },
  },
]

export const mockTransportLegs: TransportLegVM[] = [
  {
    seq: 1,
    mode: "Flight",
    fromCity: "New York",
    fromCode: "JFK",
    toCity: "Paris",
    toCode: "CDG",
    departLocal: "2024-06-15T20:30:00",
    arriveLocal: "2024-06-16T09:45:00",
    durationMin: 435,
    bagsIncluded: 1,
    refundable: "Partial",
    totalPrice: 620,
    currency: "USD",
    bookingLink: "https://example.com/book",
    source: "Air France",
  },
  {
    seq: 2,
    mode: "Train",
    fromCity: "Paris",
    toCity: "Amsterdam",
    departLocal: "2024-06-18T14:20:00",
    arriveLocal: "2024-06-18T17:45:00",
    durationMin: 205,
    refundable: "Refundable",
    totalPrice: 85,
    currency: "USD",
    bookingLink: "https://example.com/train",
    source: "Thalys",
  },
]

export const mockStays: StayVM[] = [
  {
    city: "Paris",
    checkIn: "2024-06-16",
    checkOut: "2024-06-18",
    nights: 2,
    name: "Hotel des Arts Montmartre",
    type: "Hotel",
    roomType: "Double Room",
    cancellation: "Free",
    pricePerNight: 120,
    taxes: 15,
    currency: "USD",
    total: 255,
    link: "https://example.com/hotel",
  },
  {
    city: "Amsterdam",
    checkIn: "2024-06-18",
    checkOut: "2024-06-21",
    nights: 3,
    name: "ClinkNOORD Hostel",
    type: "Hostel",
    roomType: "Private Double",
    cancellation: "Partial",
    pricePerNight: 75,
    taxes: 12,
    currency: "USD",
    total: 237,
    link: "https://example.com/hostel",
  },
]

export const mockDailyBudgets: DailyBudgetVM[] = [
  {
    day: 1,
    date: "2024-06-16",
    city: "Paris",
    food: 45,
    localTransport: 12,
    activities: 25,
    misc: 15,
    buffer: 10,
    total: 107,
  },
  {
    day: 2,
    date: "2024-06-17",
    city: "Paris",
    food: 50,
    localTransport: 8,
    activities: 35,
    misc: 20,
    buffer: 11,
    total: 124,
  },
]

export const mockCostSummary: CostSummaryVM = {
  flightsTotal: 1240,
  groundTotal: 320,
  stayTotal: 1680,
  dailyBudgetsTotal: 840,
  serviceFee: 50,
  bufferPercent: 10,
  grandTotal: 4130,
  perPersonTotal: 2065,
  currency: "USD",
}

export const mockItineraryDays: ItineraryDay[] = [
  {
    day: 1,
    date: "2024-06-16",
    city: "Paris",
    country: "France",
    activities: ["Arrive at CDG", "Check into hotel", "Evening stroll along Seine"],
    dailyTotal: 107,
    isLocked: false,
  },
  {
    day: 2,
    date: "2024-06-17",
    city: "Paris",
    country: "France",
    activities: ["Visit Louvre Museum", "Lunch in Marais", "Climb Eiffel Tower"],
    dailyTotal: 124,
    isLocked: true,
  },
  {
    day: 3,
    date: "2024-06-18",
    city: "Amsterdam",
    country: "Netherlands",
    activities: ["Train to Amsterdam", "Canal cruise", "Visit Anne Frank House"],
    dailyTotal: 95,
    isLocked: true,
  },
]
